import type { Metadata } from "next";
import Link from "next/link";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Breadcrumb from "@/components/Breadcrumb";
import RandomPicker from "@/components/RandomPicker";
import { pickerItems, type PickerKind } from "@/data/randomPickers";
import { SITE_URL, hreflangAlternates } from "@/i18n/config";
export const PICKER_PAGES = {
  object: { slug:"random-object-generator", name:"Random Object Generator", title:"Random Object Generator — Everyday Objects to Pick | Random Topics", description:"Pick random physical objects for drawing, guessing games or creative exercises. Filter everyday categories, draw 1–10 at a time, and copy without repeats.", intro:"A physical object for your next sketch, guessing game or creative warm-up.", steps:["Choose a category or leave all six mixed together.","Pick one object for a sketch, or draw a batch for a guessing game.","Copy the names, then use your own descriptions or drawings."], faq:[ ["What counts as a random object?","This collection contains 72 distinct physical things from home, kitchen, desk, workshop, outdoors and travel. It does not mix in people, places, countries or abstract concepts."], ["Can I get several objects without repeats?","Choose 1, 3, 5 or 10 results. A tab-local round tracks every shown object across filters. A short final batch is labelled; it never fills the batch with repeats. Explicitly start a fresh round when a selection is exhausted."], ["How is this different from drawing prompts?","This picker gives object names for your own activity. The drawing generator gives a full subject and starting tip, including simple sketch references for selected ideas."] ] },
  state: { slug:"random-state-generator", name:"Random US State Generator", title:"Random US State Generator — 50 States & Capital Practice | Random Topics", description:"Pick a random US state from all 50, including Alaska and Hawaii. Filter Census regions or the contiguous 48, reveal capitals, copy state names and avoid repeats.", intro:"Pick from all 50 US states. Try naming the capital before you reveal it.", steps:["Start with all 50 states, or choose a Census region.","For a lower-48 exercise, turn on Contiguous 48 states only.","Guess the capital, reveal the answer, and pick another state."], faq:[ ["Which states are included?","All 50 states, including Alaska and Hawaii. Washington means Washington state; its capital is Olympia. Washington, DC and the US territories are not states and are not in this pool."], ["What regions does the filter use?","The four Census regions: Northeast has 9 states, Midwest 12, South 16 and West 13. DC appears in Census geography, but is excluded here because this tool draws states only."], ["Can I use this for capital practice?","Yes. Each result shows the state and its USPS abbreviation. Use Reveal capital after making your guess. Copy name includes the state, abbreviation and region, leaving the capital for your own quiz."] ] },
  country: { slug:"country-name-generator", name:"Country Name Generator", title:"Country Name Generator — Fictional Fantasy, Modern & Sci-fi | Random Topics", description:"Create fictional country-name ideas for stories and worldbuilding. Pick Fantasy, Modern or Sci-fi, add a kingdom or republic form, and copy a non-repeating batch.", intro:"Fictional names for a country in your story or imagined world — not a random real-country picker.", steps:["Pick Fantasy, Modern or Sci-fi for a different naming sound.","Keep just the name, or use Kingdom of… or Republic of… for your setting.","Say the name aloud and decide whether it fits your map and story."], faq:[ ["Are these real country names?","No. They are fictional suggestions made from our own naming combinations. Exact English country and territory names are screened out. Similarity to existing names, brands or fictional works is still possible."], ["Does adding Kingdom or Republic create a new unique name?","No. These are optional forms of the same name. Changing the form or style does not reset the round, so a name already shown stays out until you explicitly start a fresh round."], ["Are the suggestions unique and ready to publish?","They are unique within the tool’s current pool, not guaranteed globally unique or trademark-cleared. Check a chosen name in the context of your work before publishing it. This is a naming aid, not an AI image or geopolitical fact tool."] ] },
} as const;
export function pickerMetadata(kind: PickerKind): Metadata {
  const c=PICKER_PAGES[kind],path=`/${c.slug}`;
  return {title:{absolute:c.title},description:c.description,alternates:{canonical:path,languages:hreflangAlternates(path)},openGraph:{title:c.title,description:c.description,url:SITE_URL+path,type:"website",siteName:"Random Topics"}};
}
export default function RandomPickerPage({kind}: {kind: PickerKind}) {
  const c=PICKER_PAGES[kind],items=pickerItems(kind),groups=[...new Set(items.map(p=>p.group))];
  return <><Navbar /><main className="flex-1"><Breadcrumb items={[{label:"Home",href:"/"},{label:c.name}]} /><div className="max-w-3xl mx-auto px-4 sm:px-6 pb-12">
    <header className="py-5 sm:py-8 text-center"><h1 className="text-3xl sm:text-4xl font-extrabold" style={{fontFamily:"var(--font-display)"}}>{c.name}</h1><p className="text-base text-[var(--text-secondary)] mt-3">{c.intro}</p><p className="mt-2 text-xs text-[var(--text-secondary)]">{items.length} choices · Free · No account</p></header>
    <RandomPicker key={kind} kind={kind} />
    <section className="glass-card p-5 sm:p-8 mt-8"><h2 className="text-xl font-bold">Make your next pick useful</h2><ol className="list-decimal pl-5 mt-3 space-y-2">{c.steps.map(s=><li key={s}>{s}</li>)}</ol><p className="text-sm text-[var(--text-secondary)] mt-3">The starting example counts in your round. Progress restores in the same tab when browser storage is available; a new tab has its own round.</p></section>
    <section className="mt-8"><h2 className="text-xl font-bold">{kind === "country" ? "Browse the fictional name pool" : kind === "state" ? "The 50-state reference" : "Browse the object collection"}</h2><div className="mt-4 space-y-3">{groups.map(group=><details key={group} className="glass-card p-4"><summary className="capitalize font-semibold cursor-pointer min-h-11">{group === "scifi" ? "Sci-fi" : group} · {items.filter(p=>p.group===group).length} choices</summary><ul className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-3 text-sm">{items.filter(p=>p.group===group).map(p=><li key={p.id}>{p.name}{kind === "state" && <> ({p.id}) · Capital: {p.capital}</>}</li>)}</ul></details>)}</div>
      {kind === "state" && <p className="text-xs text-[var(--text-secondary)] mt-4">Regions follow the <a href="https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf" className="underline">US Census region map</a>; abbreviations follow <a href="https://pe.usps.com/text/pub28/28apb.htm" className="underline">USPS</a>. This pool excludes DC and territories.</p>}
    </section>
    <section className="glass-card p-5 sm:p-8 mt-8"><h2 className="text-xl font-bold">Questions about this picker</h2>{c.faq.map(([q,a])=><div key={q} className="mt-4"><h3 className="font-bold">{q}</h3><p className="mt-2 text-[var(--text-secondary)]">{a}</p></div>)}</section>
    <section className="mt-8"><h2 className="font-bold">Choose another kind of inspiration</h2><div className="flex flex-wrap gap-4 mt-3">{Object.entries(PICKER_PAGES).filter(([k])=>k!==kind).map(([k,p])=><Link key={k}href={`/${p.slug}`}className="underline text-[var(--neon-cyan)]">{p.name}</Link>)}<Link href="/random-drawing-generator" className="underline text-[var(--neon-cyan)]">Random Drawing Generator</Link></div></section>
  </div><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"WebApplication",name:c.name,url:`${SITE_URL}/${c.slug}`,description:c.description,applicationCategory:kind==="state"?"EducationalApplication":"EntertainmentApplication",operatingSystem:"Any",isAccessibleForFree:true,offers:{"@type":"Offer",price:"0",priceCurrency:"USD"}})}} /></main><Footer /></>;
}
