import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Terms of service for randomtopics.app - Random Topic Generator.",
  alternates: {
    canonical: "/terms",
  },
};

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="flex-1 px-4 sm:px-6 py-12">
        <div className="max-w-3xl mx-auto space-y-10">
          {/* Header */}
          <section className="text-center space-y-4">
            <h1
              className="text-4xl sm:text-5xl font-bold"
              style={{ fontFamily: "var(--font-display)" }}
            >
              Terms of <span className="gradient-text">Service</span>
            </h1>
            <p className="text-sm text-[var(--text-muted)]">
              Last updated: April 2026
            </p>
          </section>

          {/* Acceptance */}
          <section className="glass-card p-8 space-y-4">
            <h2
              className="text-2xl font-semibold text-[var(--text-primary)]"
              style={{ fontFamily: "var(--font-display)" }}
            >
              Acceptance of Terms
            </h2>
            <p className="text-[var(--text-secondary)] leading-relaxed">
              By accessing and using{" "}
              <strong className="text-[var(--text-primary)]">randomtopics.app</strong>,
              you agree to be bound by these Terms of Service. If you do not
              agree with any part of these terms, please do not use the website.
            </p>
          </section>

          {/* Description of Service */}
          <section className="glass-card p-8 space-y-4">
            <h2
              className="text-2xl font-semibold text-[var(--text-primary)]"
              style={{ fontFamily: "var(--font-display)" }}
            >
              Description of Service
            </h2>
            <p className="text-[var(--text-secondary)] leading-relaxed">
              Random Topics is a free online tool that generates random topics
              for conversations, writing prompts, debates, speeches, and
              icebreakers. The service is provided &quot;as is&quot; without any
              warranties or guarantees of availability.
            </p>
          </section>

          {/* Use of Content */}
          <section className="glass-card p-8 space-y-4">
            <h2
              className="text-2xl font-semibold text-[var(--text-primary)]"
              style={{ fontFamily: "var(--font-display)" }}
            >
              Use of Content
            </h2>
            <p className="text-[var(--text-secondary)] leading-relaxed">
              Topics generated by this tool are free to use for personal,
              educational, and commercial purposes. You may use generated topics
              in your classrooms, presentations, blog posts, social media, and
              any other content without attribution, though a link back to
              randomtopics.app is always appreciated.
            </p>
          </section>

          {/* AI-Generated Content */}
          <section className="glass-card p-8 space-y-4">
            <h2
              className="text-2xl font-semibold text-[var(--text-primary)]"
              style={{ fontFamily: "var(--font-display)" }}
            >
              AI-Generated Content
            </h2>
            <p className="text-[var(--text-secondary)] leading-relaxed">
              Some topics are generated using artificial intelligence. While we
              strive for quality and accuracy, AI-generated content may
              occasionally be inaccurate, repetitive, or inappropriate. We are
              not responsible for any consequences arising from the use of
              AI-generated topics.
            </p>
          </section>

          {/* Prohibited Use */}
          <section className="glass-card p-8 space-y-4">
            <h2
              className="text-2xl font-semibold text-[var(--text-primary)]"
              style={{ fontFamily: "var(--font-display)" }}
            >
              Prohibited Use
            </h2>
            <p className="text-[var(--text-secondary)] leading-relaxed">
              You agree not to use this service to:
            </p>
            <ul className="list-disc list-inside space-y-2 text-[var(--text-secondary)]">
              <li>Violate any applicable laws or regulations</li>
              <li>Attempt to disrupt or overload the service</li>
              <li>Scrape or harvest data in an automated fashion beyond reasonable personal use</li>
              <li>Redistribute the service&apos;s curated content databases in bulk</li>
            </ul>
          </section>

          {/* Limitation of Liability */}
          <section className="glass-card p-8 space-y-4">
            <h2
              className="text-2xl font-semibold text-[var(--text-primary)]"
              style={{ fontFamily: "var(--font-display)" }}
            >
              Limitation of Liability
            </h2>
            <p className="text-[var(--text-secondary)] leading-relaxed">
              Random Topics and its creators shall not be liable for any direct,
              indirect, incidental, or consequential damages arising from your
              use of this service. The service is provided for informational and
              entertainment purposes only.
            </p>
          </section>

          {/* Changes */}
          <section className="glass-card p-8 space-y-4">
            <h2
              className="text-2xl font-semibold text-[var(--text-primary)]"
              style={{ fontFamily: "var(--font-display)" }}
            >
              Changes to Terms
            </h2>
            <p className="text-[var(--text-secondary)] leading-relaxed">
              We reserve the right to modify these terms at any time. Changes
              will be posted on this page with an updated date. Continued use of
              the service after changes constitutes acceptance of the new terms.
            </p>
          </section>

          {/* Contact */}
          <section className="glass-card p-8 space-y-4">
            <h2
              className="text-2xl font-semibold text-[var(--text-primary)]"
              style={{ fontFamily: "var(--font-display)" }}
            >
              Contact
            </h2>
            <p className="text-[var(--text-secondary)] leading-relaxed">
              If you have questions about these terms, visit us at{" "}
              <a
                href="https://randomtopics.app"
                className="text-[var(--accent-blue)] hover:underline"
              >
                randomtopics.app
              </a>
              .
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </>
  );
}
