// Real React effects + mocked Google SDK/CMP. Every URL is fulfilled locally or
// blocked; no real advertising, analytics, login or payment network is allowed.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdtempSync,writeFileSync,readFileSync,rmSync} from 'node:fs';
import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';
const require=createRequire(import.meta.url),root=resolve(import.meta.dirname,'..');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const temp=mkdtempSync(join(tmpdir(),'rt-ad-mock-'));
const put=(n,s)=>{const p=join(temp,n);writeFileSync(p,s);return p};
const loader=put('loader.cjs',`const ts=require(${JSON.stringify(require.resolve('typescript'))});module.exports=s=>ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.ReactJSX}}).outputText`);
const link=put('link.tsx','export default function Link(p){return <a {...p}/>;}');
const auth=put('auth.ts',"const listeners=new Set();window.__adAuthChange=(user,event='SIGNED_IN')=>{window.__adUser=user;for(const listener of listeners)listener(event,user?{user:{id:user}}:null)};export async function speechClient(){if(window.__adSessionFailure)throw Error('Synthetic auth unavailable');return{auth:{getSession:async()=>({data:{session:window.__adUser?{access_token:'SYNTHETIC',user:{id:window.__adUser}}:null},error:null}),onAuthStateChange(cb){listeners.add(cb);queueMicrotask(()=>{if(listeners.has(cb))cb('INITIAL_SESSION',window.__adUser?{user:{id:window.__adUser}}:null)});return{data:{subscription:{unsubscribe(){listeners.delete(cb)}}}}}}}");
const entry=put('entry.tsx',`import React,{StrictMode}from'react';import{createRoot}from'react-dom/client';import Ad from '@/components/ArticleAdvertisement';const root=createRoot(document.getElementById('root'));window.__draw=()=>root.render(<StrictMode><div style={{height:window.__offscreen?1600:0}}/><Ad path={location.pathname} slot="8217822741"/><p id="after">Content after the slot</p></StrictMode>);window.__remove=()=>root.render(<p>Content remains available</p>);window.__draw();`);
const {webpack}=require('next/dist/compiled/webpack/webpack');
await new Promise((ok,fail)=>webpack({mode:'development',devtool:false,entry,output:{path:temp,filename:'bundle.js'},resolve:{extensions:['.tsx','.ts','.js'],modules:[resolve(root,'node_modules')],alias:{'next/link':link,'@':resolve(root,'src'),[resolve(root,'src/lib/speech/client.ts')]:auth}},module:{rules:[{test:/\.tsx?$/,use:loader}]}},(e,s)=>e||s.hasErrors()?fail(e||Error(s.toString({all:false,errors:true}))):ok()));
const bundle=readFileSync(join(temp,'bundle.js'));
const html='<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box}body{margin:0}p{margin:0}button{min-height:44px}.rt-article-ad{width:100%;height:456px;padding:24px 0;margin:0 auto 40px}.mb-3{margin-bottom:12px}.mt-6{margin-top:24px}.h-16{height:64px}.h-11{height:44px}.block{display:block}.text-center{text-align:center}@media(max-width:319px){.rt-article-ad{display:none}}</style><div id="root"></div><script src="/fixture.js"></script></html>';
import {mockSdk} from './lib/adsense-mock-sdk.mjs';
const granted={gdprApplies:true,cmpStatus:'loaded',eventStatus:'useractioncomplete',purpose:{consents:{1:true}},vendor:{consents:{755:true}}};
const denied={...granted,purpose:{consents:{1:false}}};
const gppClear={gppVersion:'1.1',cmpStatus:'loaded',signalStatus:'ready',applicableSections:[7],supportedAPIs:['7:usnat'],parsedSections:{usnat:[{SaleOptOut:2,SharingOptOut:2,TargetedAdvertisingOptOut:2},{Gpc:false}]}};
const browser=await chromium.launch({headless:true,chromiumSandbox:true});const results=[],errors=[];
const output=process.env.AD_EVIDENCE||'/tmp/adsense-browser';
async function fixture(options={}){
 const context=await browser.newContext({viewport:{width:options.width||390,height:844},serviceWorkers:'block'});let sdkLoads=0,cmpLoads=0,blocked=0,documents=0,apiCalls=0,closing=false;
 let backend=options.paid?'paid':options.entitlementFailure?'failure':'free',release,nextHold;
 const held=options.entitlementHold?new Promise(r=>release=r):null;
 const handle=async route=>{const req=route.request(),u=new URL(req.url());
  if(u.hostname==='fundingchoicesmessages.google.com'){cmpLoads++;return route.fulfill({contentType:'text/javascript',body:'/* mock CMP supplied by the mock SDK */'})}
  if(u.hostname==='pagead2.googlesyndication.com'&&u.pathname==='/pagead/js/adsbygoogle.js'){sdkLoads++;if(options.scriptFailure)return route.abort();if(options.timeout||options.lateSdk)await new Promise(r=>setTimeout(r,options.lateSdk?400:100));return route.fulfill({contentType:'text/javascript',body:mockSdk})}
  if(u.hostname===new URL(options.origin||'https://randomtopics.app').hostname){
   if(u.pathname==='/fixture.js')return route.fulfill({contentType:'text/javascript',body:bundle});
   if(u.pathname==='/api/speech/ad-entitlement'){apiCalls++;const state=backend,member=Boolean(req.headers().authorization),hold=apiCalls===1?held:nextHold;nextHold=undefined;if(hold)await hold;if(options.entitlementTimeout)await new Promise(r=>setTimeout(r,200));return route.fulfill({status:state==='failure'?503:200,contentType:'application/json',body:JSON.stringify({version:'speech-ad-v1',audience:member?'verified_session':'signed_out',adFree:state==='paid'})})}
   if(u.pathname.startsWith('/api/'))return route.abort();documents++;return route.fulfill({contentType:'text/html',body:html})
  }blocked++;return route.abort()
 };
 await context.route('**/*',route=>handle(route).catch(e=>{if(!closing&&!/closed|cancel|abort/i.test(e.message))throw e}));
 await context.addInitScript(({options,granted,denied})=>{window.__privacyOptions=options;window.__adUser=options.user===undefined?'fixture-member':options.user;window.__adSessionFailure=Boolean(options.sessionFailure);window.__consent=options.denied?denied:options.pending?{...granted,eventStatus:'cmpuishown'}:options.nonEu?{...granted,gdprApplies:false}:granted;if(options.sparseNonEu)window.__consent={gdprApplies:false,cmpStatus:"loaded"};if(options.unknownRegion)delete window.__consent.gdprApplies;if(options.cmpError)window.__consent.cmpStatus="error";window.__usStatus=options.usStatus??1;window.__missingCmp=options.missingCmp;window.__offscreen=options.offscreen;if(options.qa)sessionStorage.setItem('rt_usage_qa','1');window.__gpc=Boolean(options.gpc);Object.defineProperty(navigator,'globalPrivacyControl',{configurable:true,get:()=>window.__gpc});if(options.storageBlocked)Storage.prototype.getItem=()=>{throw Error('synthetic storage refusal')};if(options.timeout||options.entitlementTimeout){const set=window.setTimeout;window.setTimeout=(f,ms,...args)=>set(f,(options.timeout&&ms===10000)||(options.entitlementTimeout&&ms===8000)?10:ms,...args)}}, {options,granted,denied});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto((options.origin||'https://randomtopics.app')+(options.path||'/'));await page.locator('aside').waitFor({state:'attached'});await page.waitForTimeout(180);
 return {page,context,loads:()=>sdkLoads,cmp:()=>cmpLoads,documents:()=>documents,blocked:()=>blocked,api:()=>apiCalls,backend:state=>{backend=state},holdNext:()=>{nextHold=new Promise(r=>release=r)},release:()=>release?.(),stats:()=>page.evaluate(()=>window.__mock||{prepared:0,resumes:0,requests:0}),close:async()=>{closing=true;release?.();await context.close()}};
}
const test=async(name,options,fn)=>{const f=await fixture(options);try{await fn(f);results.push({name,pass:true})}catch(e){results.push({name,pass:false,error:e.message})}finally{await f.close()}};
try{
 for(const options of [{paid:true},{entitlementFailure:true},{sessionFailure:true},{entitlementTimeout:true}])await test('Paid/unknown/failure never bootstraps CMP or SDK '+JSON.stringify(options),options,async f=>{assert.equal(f.loads(),0);assert.equal(f.cmp(),0);assert.equal(await f.page.locator('script[data-rt-adsense],script[data-rt-cmp]').count(),0);assert.equal(await f.page.locator('aside').isVisible(),false)});
 await test('Slow eligibility does not prepare a queue or bootstrap scripts',{entitlementHold:true},async f=>{assert.equal(f.loads(),0);assert.equal(f.cmp(),0);assert.equal(await f.page.evaluate(()=>typeof window.adsbygoogle),'undefined');f.release();await f.page.waitForFunction(()=>window.__mock?.requests===1);assert.equal(f.loads(),1)});
 await test('Signed-out visitor remains eligible only after server check',{user:null},async f=>{assert.ok(f.api()>=1);assert.equal(f.loads(),1);assert.equal((await f.stats()).requests,1)});
 for(const reason of ['paid','failure','switch','logout','bfcache','unmount'])await test('Loaded SDK exits entire document without reloading ads: '+reason,{},async f=>{
  assert.equal(f.loads(),1);const docs=f.documents();f.backend(reason==='paid'?'paid':reason==='failure'?'failure':'free');
  await f.page.evaluate(reason=>{if(reason==='switch')window.__adAuthChange('other-member');else if(reason==='logout')window.__adAuthChange(null,'SIGNED_OUT');else if(reason==='bfcache')dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}));else if(reason==='unmount')window.__remove();else dispatchEvent(new Event('focus'))},reason);
  await f.page.waitForURL(url=>url.searchParams.get('rt_ads')==='off');await f.page.waitForLoadState('load');await f.page.waitForTimeout(80);
  assert.ok(f.documents()>docs);assert.equal(f.loads(),1);assert.equal(f.cmp(),1);assert.equal(await f.page.evaluate(()=>typeof window.adsbygoogle),'undefined');assert.equal(await f.page.locator('script[data-rt-adsense],script[data-rt-cmp]').count(),0);assert.equal(await f.page.locator('aside').isVisible(),false);
 });
 await test('Account switch while SDK is loading cannot revive the discarded runtime',{lateSdk:true},async f=>{assert.equal(f.loads(),1);await f.page.evaluate(()=>window.__adAuthChange('other-member'));await f.page.waitForURL(url=>url.searchParams.get('rt_ads')==='off');await f.page.waitForTimeout(450);assert.equal(f.loads(),1);assert.equal(await f.page.evaluate(()=>typeof window.adsbygoogle),'undefined')});
 await test('Old free entitlement result cannot override newly paid identity',{entitlementHold:true},async f=>{f.backend('paid');await f.page.evaluate(()=>window.__adAuthChange('other-member'));await f.page.waitForTimeout(70);f.release();await f.page.waitForTimeout(80);assert.equal(f.loads(),0);assert.equal(f.cmp(),0);assert.equal(await f.page.locator('aside').isVisible(),false)});
 await test('Paid-to-signed-out rechecks before its first SDK',{paid:true},async f=>{assert.equal(f.loads(),0);f.backend('free');await f.page.evaluate(()=>window.__adAuthChange(null,'SIGNED_OUT'));await f.page.waitForFunction(()=>window.__mock?.requests===1);assert.equal(f.loads(),1)});
 await test('Same-account free refresh pauses then resumes without preparing or filling twice',{},async f=>{assert.equal((await f.stats()).requests,1);const resumes=(await f.stats()).resumes;f.holdNext();await f.page.evaluate(()=>window.__adAuthChange('fixture-member','TOKEN_REFRESHED'));await f.page.waitForFunction(()=>window.__mock.pause===1);assert.equal((await f.stats()).requests,1);f.release();await f.page.waitForFunction(()=>window.__mock.pause===0);assert.equal(f.loads(),1);assert.equal((await f.stats()).prepared,1);assert.equal((await f.stats()).requests,1);assert.equal((await f.stats()).resumes,resumes+1)});
 await test('StrictMode: one slot preparation and one NPA/RDP release',{},async f=>{assert.equal(f.loads(),1);assert.deepEqual(await f.stats(),{prepared:1,resumes:1,requests:1,pause:0,npa:1,reopen:0});assert.equal(await f.page.locator('ins').getAttribute('data-restrict-data-processing'),'1');await f.page.evaluate(()=>window.__draw());await f.page.waitForTimeout(60);assert.equal((await f.stats()).requests,1);assert.equal((await f.stats()).prepared,1)});
 await test('Known denied consent never unpauses', {denied:true},async f=>{assert.equal((await f.stats()).requests,0);assert.equal((await f.stats()).pause,1)});
 await test('Unknown choice waits; explicit consent releases once',{pending:true},async f=>{assert.equal((await f.stats()).requests,0);await f.page.evaluate(d=>window.__setConsent(d),granted);await f.page.waitForTimeout(50);assert.equal((await f.stats()).requests,1)});
 await test('Missing CMP remains paused without fallback',{missingCmp:true},async f=>assert.equal((await f.stats()).requests,0));
 await test('Confirmed non-applicable regional status allows only NPA/RDP',{nonEu:true,usStatus:1},async f=>assert.equal((await f.stats()).requests,1));
 await test('US NOT_OPTED_OUT uses RDP without claiming consent',{nonEu:true,usStatus:2,gpp:gppClear},async f=>{assert.equal((await f.stats()).requests,1);assert.equal(await f.page.evaluate(()=>window.__mockRdp),'1')});
 await test('Configured applicable US message waits for GPP updates',{nonEu:true,usStatus:2},async f=>assert.equal((await f.stats()).requests,0));
 for(const status of [0,3])await test('Unverified/opted-out US state status '+status,{nonEu:true,usStatus:status},async f=>assert.equal((await f.stats()).requests,0));
 for(const options of [{nonEu:true,missingUs:true},{sparseNonEu:true,missingUs:true},{nonEu:true,emptyUs:true}])await test('Missing optional US API uses known non-EU RDP '+JSON.stringify(options),options,async f=>{assert.equal((await f.stats()).requests,1);assert.equal((await f.stats()).npa,1);assert.equal(await f.page.evaluate(()=>window.__mockRdp),'1')});
 for(const options of [{unknownRegion:true,missingUs:true},{cmpError:true,missingUs:true},{nonEu:true,usThrows:true},{nonEu:true,usUndefined:true},{nonEu:true,usEnumMissing:true},{nonEu:true,usGetterMissing:true}])await test('Unknown/error signal stays paused '+JSON.stringify(options),options,async f=>assert.equal((await f.stats()).requests,0));
 await test('Installed US interface waits for its data callback',{nonEu:true,delayedUs:true,gpp:gppClear},async f=>{assert.equal((await f.stats()).requests,0);await f.page.evaluate(()=>window.__releaseUs(2));await f.page.waitForTimeout(50);assert.equal((await f.stats()).requests,1)});
 const gpp={gppVersion:'1.1',cmpStatus:'loaded',signalStatus:'ready',applicableSections:[7],supportedAPIs:['7:usnat'],parsedSections:{usnat:[{SaleOptOut:2,SharingOptOut:2,TargetedAdvertisingOptOut:2},{Gpc:false}]}};
 const opted={...gpp,parsedSections:{usnat:[{SaleOptOut:1,SharingOptOut:2,TargetedAdvertisingOptOut:2}]}};
 for(const [name,data,requests] of [['no section',{...gpp,applicableSections:[-1]},1],['clear',gpp,1],['opted out',opted,0],['pending',{...gpp,signalStatus:'not ready'},0],['malformed',{...gpp,parsedSections:{}},0],['GPC',{...gpp,parsedSections:{usnat:[{SaleOptOut:2,SharingOptOut:2,TargetedAdvertisingOptOut:2},{Gpc:true}]}},0]])await test('GPP initial '+name,{nonEu:true,missingUs:true,gpp:data},async f=>assert.equal((await f.stats()).requests,requests));
 await test('GPP ready transition releases only one RDP request',{nonEu:true,missingUs:true,gpp:{...gpp,signalStatus:'not ready'}},async f=>{assert.equal((await f.stats()).requests,0);await f.page.evaluate(d=>{window.__setGpp(d);window.__setGpp(d)},gpp);await f.page.waitForTimeout(60);assert.equal((await f.stats()).requests,1)});
 for(const reason of ['US opt-out','GPP opt-out','GPP error','GPC','EU refusal'])await test('Privacy withdrawal exits old non-EU document: '+reason,{nonEu:true,missingUs:reason!=='US opt-out',gpp},async f=>{
  assert.equal((await f.stats()).requests,1);const before=f.documents();
  await f.page.evaluate(({reason,opted,denied})=>{if(reason==='US opt-out')window.__releaseUs(3);else if(reason==='GPP opt-out')window.__setGpp(opted);else if(reason==='GPP error')window.__setGpp(undefined,false,'error');else if(reason==='GPC'){window.__gpc=true;dispatchEvent(new Event('focus'))}else window.__setConsent(denied)},{reason,opted,denied});
  await f.page.waitForURL(url=>url.searchParams.get('rt_ads')==='off');await f.page.waitForLoadState('load');assert.ok(f.documents()>before);assert.equal(f.loads(),1);assert.equal(await f.page.evaluate(()=>typeof window.adsbygoogle),'undefined');
 });
 await test('Non-EU changing to EU pauses and resumes after final choice without another slot fill',{nonEu:true,missingUs:true},async f=>{assert.equal((await f.stats()).requests,1);const resumes=(await f.stats()).resumes;await f.page.evaluate(d=>window.__setConsent({...d,eventStatus:'cmpuishown'}),granted);assert.equal((await f.stats()).pause,1);assert.equal(f.documents(),1);await f.page.evaluate(d=>window.__setConsent(d),granted);await f.page.waitForFunction(()=>window.__mock.pause===0);assert.equal((await f.stats()).resumes,resumes+1);assert.equal((await f.stats()).requests,1);assert.equal((await f.stats()).prepared,1)});
 for(const options of [{paid:true},{entitlementFailure:true},{sessionFailure:true},{entitlementTimeout:true},{gpc:true},{denied:true}])await test('Non-EU policy preserves exclusion '+JSON.stringify(options),{nonEu:!options.denied,missingUs:true,...options},async f=>{assert.equal((await f.stats()).requests,0);if(!options.denied){assert.equal(f.loads(),0);assert.equal(f.cmp(),0)}});
 await test('New non-EU path still retires on paid upgrade',{nonEu:true,missingUs:true},async f=>{assert.equal((await f.stats()).requests,1);f.backend('paid');await f.page.evaluate(()=>dispatchEvent(new Event('focus')));await f.page.waitForURL(url=>url.searchParams.get('rt_ads')==='off');await f.page.waitForLoadState('load');assert.equal(f.loads(),1);assert.equal(await f.page.evaluate(()=>typeof window.adsbygoogle),'undefined')});
 await test('A missing RDP attribute cannot release an ad',{nonEu:true,missingUs:true,entitlementHold:true},async f=>{await f.page.locator('ins').evaluate(el=>el.removeAttribute('data-restrict-data-processing'));f.release();await f.page.waitForTimeout(100);assert.equal((await f.stats()).requests,0)});
 for(const options of [{qa:true},{gpc:true},{storageBlocked:true},{path:'/?usage_qa=1'},{path:'/speech'},{path:'/speech/account'},{origin:'https://preview.example.test'},{width:319}])await test('No SDK under '+JSON.stringify(options),options,async f=>assert.equal(f.loads(),0));
 await test('Offscreen slot bootstraps Auto ads but prepares the manual slot only near viewport',{offscreen:true},async f=>{assert.equal(f.loads(),1);assert.equal(f.cmp(),1);assert.equal((await f.stats()).pause,0);assert.equal((await f.stats()).resumes,1);assert.equal((await f.stats()).prepared,0);assert.equal((await f.stats()).requests,0);await f.page.locator('ins').scrollIntoViewIfNeeded();await f.page.waitForFunction(()=>window.__mock.requests===1);assert.equal((await f.stats()).prepared,1);assert.equal((await f.stats()).resumes,1)});
 await test('Offscreen Auto ads pause and resume during fresh eligibility checks without a manual push',{offscreen:true},async f=>{assert.equal((await f.stats()).prepared,0);f.holdNext();await f.page.evaluate(()=>dispatchEvent(new Event('focus')));await f.page.waitForFunction(()=>window.__mock.pause===1);f.release();await f.page.waitForFunction(()=>window.__mock.pause===0);assert.equal((await f.stats()).resumes,2);assert.equal((await f.stats()).prepared,0);assert.equal((await f.stats()).requests,0)});
 await test('Offscreen Auto ads retire on paid upgrade before a manual slot is prepared',{offscreen:true},async f=>{assert.equal((await f.stats()).prepared,0);f.backend('paid');await f.page.evaluate(()=>dispatchEvent(new Event('focus')));await f.page.waitForURL(url=>url.searchParams.get('rt_ads')==='off');await f.page.waitForLoadState('load');assert.equal(f.loads(),1);assert.equal(await f.page.evaluate(()=>typeof window.adsbygoogle),'undefined')});
 await test('Offscreen Auto ads retire after privacy withdrawal without a manual request',{offscreen:true},async f=>{assert.equal((await f.stats()).prepared,0);await f.page.evaluate(d=>window.__setConsent(d),denied);await f.page.waitForURL(url=>url.searchParams.get('rt_ads')==='off');await f.page.waitForLoadState('load');assert.equal(f.loads(),1);assert.equal(await f.page.evaluate(()=>typeof window.adsbygoogle),'undefined')});
 await test('Ad blocker leaves article usable and never retries',{scriptFailure:true},async f=>{assert.equal(f.loads(),1);assert.equal((await f.stats()).requests,0);await f.page.evaluate(()=>window.__draw());await f.page.waitForTimeout(50);assert.equal(f.loads(),1);assert.ok(await f.page.locator('#after').isVisible())});
 await test('Late SDK after timeout cannot release a request',{timeout:true},async f=>assert.equal((await f.stats()).requests,0));
 await test('Privacy choices pauses; final withdrawal disposes the ad document',{},async f=>{await f.page.getByRole('button',{name:'Advertising privacy choices'}).click();assert.equal((await f.stats()).pause,1);const before=f.documents();await f.page.evaluate(d=>window.__setConsent(d),denied);await f.page.waitForTimeout(200);assert.ok(f.documents()>before)});
 for(const width of [320,390,1280])await test('Fixed slot and following content do not shift at '+width,{width,pending:true},async f=>{const a=await f.page.locator('#after').boundingBox();await f.page.evaluate(d=>window.__setConsent(d),granted);await f.page.waitForTimeout(70);assert.deepEqual(await f.page.locator('#after').boundingBox(),a);const b=await f.page.locator('ins').boundingBox();assert.equal(b.width,300);assert.equal(b.height,250);assert.ok(await f.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))});
 await test('Spanish label, privacy action and locale link',{path:'/es'},async f=>{assert.equal(await f.page.locator('aside').getAttribute('aria-label'),'Publicidad');assert.equal(await f.page.getByRole('link',{name:'Política de privacidad'}).getAttribute('href'),'/es/privacy');assert.ok(await f.page.getByRole('button',{name:'Opciones de privacidad publicitaria'}).isVisible())});
}finally{await browser.close();rmSync(temp,{recursive:true,force:true});writeFileSync(output+'.json',JSON.stringify({results,errors,realAdRequests:0},null,2))}
console.log(JSON.stringify({passed:results.filter(x=>x.pass).length,total:results.length,failures:results.filter(x=>!x.pass),errors}));assert.ok(results.every(x=>x.pass)&&!errors.length);
